# Module manifest for module '<%= $PLASTER_PARAM_ModuleName %>'
# Generated by: <%= $PLASTER_PARAM_FullName %>
# Generated on: <%= $PLASTER_Date %>

@{
    RootModule        = '<%= $PLASTER_PARAM_ModuleName %>.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = '<%= $PLASTER_Guid1 %>'
    Author            = '<%= $PLASTER_PARAM_FullName %>'
    CompanyName       = ''
    Copyright         = '(c) 2019 <%= $PLASTER_PARAM_FullName %>. All rights reserved.'
    Description       = '<%= $PLASTER_PARAM_Description %>'
    FunctionsToExport = @()
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            LicenseUri = 'https://github.com/<%= $PLASTER_PARAM_GitHubUserName %>/<%= $PLASTER_PARAM_ModuleName %>/blob/master/LICENSE'
            ProjectUri = 'https://github.com/<%= $PLASTER_PARAM_GitHubUserName %>/<%= $PLASTER_PARAM_ModuleName %>'
            # IconUri = ''
            ReleaseNotes = 'https://github.com/<%= $PLASTER_PARAM_GitHubUserName %>/<%= $PLASTER_PARAM_ModuleName %>/blob/master/ReleaseNotes.md'
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}